version: '3.8'

services:
  honeycomb-fe:
    image: shikibrekksten/honeycomb-fe:0.5.0  # Change this if you push to a registry
    ports:
      - "3080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: ["serve", "-s", "dist"]
    networks:
      - magistrala-base-net

networks:
  magistrala-base-net:
    name: magistrala-base-net
    driver: bridge
